CREATE TABLE IF NOT EXISTS "reason-alpha".trade (
  id                                bigint PRIMARY KEY,
  security_id                       bigint,
  time_in                           timestamp,
  time_out                          timestamp,
  trade_pattern_id                  bigint,
  long_short                        tinyint,
  time_frame_id                     int,
  quantity                          bigint,
  open_price                        double,
  close_price                       double,
  cost                              double,
  interest_per_day                  double,
  stop                              double,
  first_deviation                   double,
  currency_id                       int,
  home_currency_id                  double,
  home_currency_conversion_rate     double,
  account_id                        double,
  account_currency_conversion_rate  double);