CREATE TABLE IF NOT EXISTS "reason-alpha".trade (
  id                                uuid PRIMARY KEY,
  security_id                       uuid,
  time_in                           timestamp,
  time_out                          timestamp,
  trade_pattern_id                  uuid,
  long_short                        tinyint,
  time_frame_id                     uuid,
  quantity                          bigint,
  open_price                        double,
  close_price                       double,
  cost                              double,
  interest_per_day                  double,
  stop                              double,
  first_deviation                   double,
  currency_id                       uuid,
  home_currency_id                  uuid,
  home_currency_conversion_rate     double,
  account_id                        uuid,
  account_currency_conversion_rate  double,
  rank                              int);